### ISSUE TITLE
麻烦更新下locale data 

### ISSUE THREAD

**Issue by xueerli** [wang12124468/monaco-editor-nls#3]
@wang12124468 
哈喽 麻烦更新下locale 数据呗，现在右键菜单会报错，可能是有些数据找不到导致的。
![image](https://github.com/wang12124468/monaco-editor-nls/assets/35445052/768c2258-8d60-4528-97c0-e9bdfcc1a898)

![028ded88-bbe7-4bec-8cf3-8186abe5140a](https://github.com/wang12124468/monaco-editor-nls/assets/35445052/b08249c5-4df2-4d55-ab45-ff35e9125483)

monaco-editor@0.41.0

**Comment by wang12124468** [comment]
不好意思，这看起来不像国际化的问题。

你可以考虑将fork一下，进行更新，或者找找其他问题
